name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ‘1.14.0’

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.80.0
        TARGET_REPO: oolonek/oolonek.github.io
        TOKEN: ${{ secrets.BUILD_DEPLOY_SECRET }}
        CNAME: www.oolonek.xyz